/*
Config Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configmanager

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigmanagerBulkSetConfigsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigmanagerBulkSetConfigsRequest{}

// ConfigmanagerBulkSetConfigsRequest struct for ConfigmanagerBulkSetConfigsRequest
type ConfigmanagerBulkSetConfigsRequest struct {
	TenantId string `json:"tenantId"`
	Configs []BulkSetConfigsRequestConfig `json:"configs"`
	AdditionalProperties map[string]interface{}
}

type _ConfigmanagerBulkSetConfigsRequest ConfigmanagerBulkSetConfigsRequest

// NewConfigmanagerBulkSetConfigsRequest instantiates a new ConfigmanagerBulkSetConfigsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigmanagerBulkSetConfigsRequest(tenantId string, configs []BulkSetConfigsRequestConfig) *ConfigmanagerBulkSetConfigsRequest {
	this := ConfigmanagerBulkSetConfigsRequest{}
	this.TenantId = tenantId
	this.Configs = configs
	return &this
}

// NewConfigmanagerBulkSetConfigsRequestWithDefaults instantiates a new ConfigmanagerBulkSetConfigsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigmanagerBulkSetConfigsRequestWithDefaults() *ConfigmanagerBulkSetConfigsRequest {
	this := ConfigmanagerBulkSetConfigsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *ConfigmanagerBulkSetConfigsRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ConfigmanagerBulkSetConfigsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ConfigmanagerBulkSetConfigsRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetConfigs returns the Configs field value
func (o *ConfigmanagerBulkSetConfigsRequest) GetConfigs() []BulkSetConfigsRequestConfig {
	if o == nil {
		var ret []BulkSetConfigsRequestConfig
		return ret
	}

	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value
// and a boolean to check if the value has been set.
func (o *ConfigmanagerBulkSetConfigsRequest) GetConfigsOk() ([]BulkSetConfigsRequestConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Configs, true
}

// SetConfigs sets field value
func (o *ConfigmanagerBulkSetConfigsRequest) SetConfigs(v []BulkSetConfigsRequestConfig) {
	o.Configs = v
}

func (o ConfigmanagerBulkSetConfigsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigmanagerBulkSetConfigsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["configs"] = o.Configs

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ConfigmanagerBulkSetConfigsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"configs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigmanagerBulkSetConfigsRequest := _ConfigmanagerBulkSetConfigsRequest{}

	err = json.Unmarshal(data, &varConfigmanagerBulkSetConfigsRequest)

	if err != nil {
		return err
	}

	*o = ConfigmanagerBulkSetConfigsRequest(varConfigmanagerBulkSetConfigsRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tenantId")
		delete(additionalProperties, "configs")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

// GetValue returns the value of well-known types
func (o *ConfigmanagerBulkSetConfigsRequest) GetValue() interface{} {
	if o == nil || IsNil(o.Type) || IsNil(o.AdditionalProperties) {
		return nil
	}
	return o.AdditionalProperties["value"]
}
// SetValue populate the value of well-known types
func (o *ConfigmanagerBulkSetConfigsRequest) SetValue(value interface{}) {
	if o == nil || IsNil(o.Type) || IsNil(value) {
		return
	}
    if IsNil(o.AdditionalProperties) {
        o.AdditionalProperties = map[string]interface{}{}
    }
	o.AdditionalProperties["value"] = value
	return
}
type NullableConfigmanagerBulkSetConfigsRequest struct {
	value *ConfigmanagerBulkSetConfigsRequest
	isSet bool
}

func (v NullableConfigmanagerBulkSetConfigsRequest) Get() *ConfigmanagerBulkSetConfigsRequest {
	return v.value
}

func (v *NullableConfigmanagerBulkSetConfigsRequest) Set(val *ConfigmanagerBulkSetConfigsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigmanagerBulkSetConfigsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigmanagerBulkSetConfigsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigmanagerBulkSetConfigsRequest(val *ConfigmanagerBulkSetConfigsRequest) *NullableConfigmanagerBulkSetConfigsRequest {
	return &NullableConfigmanagerBulkSetConfigsRequest{value: val, isSet: true}
}

func (v NullableConfigmanagerBulkSetConfigsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigmanagerBulkSetConfigsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


