/*
configmanager/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigmanagerGetConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigmanagerGetConfigRequest{}

// ConfigmanagerGetConfigRequest struct for ConfigmanagerGetConfigRequest
type ConfigmanagerGetConfigRequest struct {
	TenantId string `json:"tenantId"`
	Key string `json:"key"`
	BusinessDomain *string `json:"businessDomain,omitempty"`
}

type _ConfigmanagerGetConfigRequest ConfigmanagerGetConfigRequest

// NewConfigmanagerGetConfigRequest instantiates a new ConfigmanagerGetConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigmanagerGetConfigRequest(tenantId string, key string) *ConfigmanagerGetConfigRequest {
	this := ConfigmanagerGetConfigRequest{}
	this.TenantId = tenantId
	this.Key = key
	return &this
}

// NewConfigmanagerGetConfigRequestWithDefaults instantiates a new ConfigmanagerGetConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigmanagerGetConfigRequestWithDefaults() *ConfigmanagerGetConfigRequest {
	this := ConfigmanagerGetConfigRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *ConfigmanagerGetConfigRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ConfigmanagerGetConfigRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ConfigmanagerGetConfigRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetKey returns the Key field value
func (o *ConfigmanagerGetConfigRequest) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *ConfigmanagerGetConfigRequest) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *ConfigmanagerGetConfigRequest) SetKey(v string) {
	o.Key = v
}

// GetBusinessDomain returns the BusinessDomain field value if set, zero value otherwise.
func (o *ConfigmanagerGetConfigRequest) GetBusinessDomain() string {
	if o == nil || IsNil(o.BusinessDomain) {
		var ret string
		return ret
	}
	return *o.BusinessDomain
}

// GetBusinessDomainOk returns a tuple with the BusinessDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigmanagerGetConfigRequest) GetBusinessDomainOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessDomain) {
		return nil, false
	}
	return o.BusinessDomain, true
}

// HasBusinessDomain returns a boolean if a field has been set.
func (o *ConfigmanagerGetConfigRequest) HasBusinessDomain() bool {
	if o != nil && !IsNil(o.BusinessDomain) {
		return true
	}

	return false
}

// SetBusinessDomain gets a reference to the given string and assigns it to the BusinessDomain field.
func (o *ConfigmanagerGetConfigRequest) SetBusinessDomain(v string) {
	o.BusinessDomain = &v
}

func (o ConfigmanagerGetConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigmanagerGetConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["key"] = o.Key
	if !IsNil(o.BusinessDomain) {
		toSerialize["businessDomain"] = o.BusinessDomain
	}
	return toSerialize, nil
}

func (o *ConfigmanagerGetConfigRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigmanagerGetConfigRequest := _ConfigmanagerGetConfigRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigmanagerGetConfigRequest)

	if err != nil {
		return err
	}

	*o = ConfigmanagerGetConfigRequest(varConfigmanagerGetConfigRequest)

	return err
}

type NullableConfigmanagerGetConfigRequest struct {
	value *ConfigmanagerGetConfigRequest
	isSet bool
}

func (v NullableConfigmanagerGetConfigRequest) Get() *ConfigmanagerGetConfigRequest {
	return v.value
}

func (v *NullableConfigmanagerGetConfigRequest) Set(val *ConfigmanagerGetConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigmanagerGetConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigmanagerGetConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigmanagerGetConfigRequest(val *ConfigmanagerGetConfigRequest) *NullableConfigmanagerGetConfigRequest {
	return &NullableConfigmanagerGetConfigRequest{value: val, isSet: true}
}

func (v NullableConfigmanagerGetConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigmanagerGetConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


