/*
configmanager/service.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigmanagerGetTenantIdByCodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigmanagerGetTenantIdByCodeRequest{}

// ConfigmanagerGetTenantIdByCodeRequest struct for ConfigmanagerGetTenantIdByCodeRequest
type ConfigmanagerGetTenantIdByCodeRequest struct {
	Code string `json:"code"`
}

type _ConfigmanagerGetTenantIdByCodeRequest ConfigmanagerGetTenantIdByCodeRequest

// NewConfigmanagerGetTenantIdByCodeRequest instantiates a new ConfigmanagerGetTenantIdByCodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigmanagerGetTenantIdByCodeRequest(code string) *ConfigmanagerGetTenantIdByCodeRequest {
	this := ConfigmanagerGetTenantIdByCodeRequest{}
	this.Code = code
	return &this
}

// NewConfigmanagerGetTenantIdByCodeRequestWithDefaults instantiates a new ConfigmanagerGetTenantIdByCodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigmanagerGetTenantIdByCodeRequestWithDefaults() *ConfigmanagerGetTenantIdByCodeRequest {
	this := ConfigmanagerGetTenantIdByCodeRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *ConfigmanagerGetTenantIdByCodeRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ConfigmanagerGetTenantIdByCodeRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ConfigmanagerGetTenantIdByCodeRequest) SetCode(v string) {
	o.Code = v
}

func (o ConfigmanagerGetTenantIdByCodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigmanagerGetTenantIdByCodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	return toSerialize, nil
}

func (o *ConfigmanagerGetTenantIdByCodeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigmanagerGetTenantIdByCodeRequest := _ConfigmanagerGetTenantIdByCodeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigmanagerGetTenantIdByCodeRequest)

	if err != nil {
		return err
	}

	*o = ConfigmanagerGetTenantIdByCodeRequest(varConfigmanagerGetTenantIdByCodeRequest)

	return err
}

type NullableConfigmanagerGetTenantIdByCodeRequest struct {
	value *ConfigmanagerGetTenantIdByCodeRequest
	isSet bool
}

func (v NullableConfigmanagerGetTenantIdByCodeRequest) Get() *ConfigmanagerGetTenantIdByCodeRequest {
	return v.value
}

func (v *NullableConfigmanagerGetTenantIdByCodeRequest) Set(val *ConfigmanagerGetTenantIdByCodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigmanagerGetTenantIdByCodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigmanagerGetTenantIdByCodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigmanagerGetTenantIdByCodeRequest(val *ConfigmanagerGetTenantIdByCodeRequest) *NullableConfigmanagerGetTenantIdByCodeRequest {
	return &NullableConfigmanagerGetTenantIdByCodeRequest{value: val, isSet: true}
}

func (v NullableConfigmanagerGetTenantIdByCodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigmanagerGetTenantIdByCodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


