/*
Config Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package configmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkSetConfigsRequestConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkSetConfigsRequestConfig{}

// BulkSetConfigsRequestConfig struct for BulkSetConfigsRequestConfig
type BulkSetConfigsRequestConfig struct {
	Key string `json:"key"`
	Value string `json:"value"`
	BusinessDomain *string `json:"businessDomain,omitempty"`
}

type _BulkSetConfigsRequestConfig BulkSetConfigsRequestConfig

// NewBulkSetConfigsRequestConfig instantiates a new BulkSetConfigsRequestConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkSetConfigsRequestConfig(key string, value string) *BulkSetConfigsRequestConfig {
	this := BulkSetConfigsRequestConfig{}
	this.Key = key
	this.Value = value
	return &this
}

// NewBulkSetConfigsRequestConfigWithDefaults instantiates a new BulkSetConfigsRequestConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkSetConfigsRequestConfigWithDefaults() *BulkSetConfigsRequestConfig {
	this := BulkSetConfigsRequestConfig{}
	return &this
}

// GetKey returns the Key field value
func (o *BulkSetConfigsRequestConfig) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *BulkSetConfigsRequestConfig) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *BulkSetConfigsRequestConfig) SetKey(v string) {
	o.Key = v
}

// GetValue returns the Value field value
func (o *BulkSetConfigsRequestConfig) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *BulkSetConfigsRequestConfig) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *BulkSetConfigsRequestConfig) SetValue(v string) {
	o.Value = v
}

// GetBusinessDomain returns the BusinessDomain field value if set, zero value otherwise.
func (o *BulkSetConfigsRequestConfig) GetBusinessDomain() string {
	if o == nil || IsNil(o.BusinessDomain) {
		var ret string
		return ret
	}
	return *o.BusinessDomain
}

// GetBusinessDomainOk returns a tuple with the BusinessDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkSetConfigsRequestConfig) GetBusinessDomainOk() (*string, bool) {
	if o == nil || IsNil(o.BusinessDomain) {
		return nil, false
	}
	return o.BusinessDomain, true
}

// HasBusinessDomain returns a boolean if a field has been set.
func (o *BulkSetConfigsRequestConfig) HasBusinessDomain() bool {
	if o != nil && !IsNil(o.BusinessDomain) {
		return true
	}

	return false
}

// SetBusinessDomain gets a reference to the given string and assigns it to the BusinessDomain field.
func (o *BulkSetConfigsRequestConfig) SetBusinessDomain(v string) {
	o.BusinessDomain = &v
}

func (o BulkSetConfigsRequestConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkSetConfigsRequestConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["value"] = o.Value
	if !IsNil(o.BusinessDomain) {
		toSerialize["businessDomain"] = o.BusinessDomain
	}
	return toSerialize, nil
}

func (o *BulkSetConfigsRequestConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkSetConfigsRequestConfig := _BulkSetConfigsRequestConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkSetConfigsRequestConfig)

	if err != nil {
		return err
	}

	*o = BulkSetConfigsRequestConfig(varBulkSetConfigsRequestConfig)

	return err
}

type NullableBulkSetConfigsRequestConfig struct {
	value *BulkSetConfigsRequestConfig
	isSet bool
}

func (v NullableBulkSetConfigsRequestConfig) Get() *BulkSetConfigsRequestConfig {
	return v.value
}

func (v *NullableBulkSetConfigsRequestConfig) Set(val *BulkSetConfigsRequestConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkSetConfigsRequestConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkSetConfigsRequestConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkSetConfigsRequestConfig(val *BulkSetConfigsRequestConfig) *NullableBulkSetConfigsRequestConfig {
	return &NullableBulkSetConfigsRequestConfig{value: val, isSet: true}
}

func (v NullableBulkSetConfigsRequestConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkSetConfigsRequestConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


